/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Donut {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'price' : bigint,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'customerPhone' : string,
  'timestamp' : bigint,
  'items' : Array<OrderItem>,
  'customerEmail' : string,
}
export interface OrderItem { 'donutId' : bigint, 'quantity' : bigint }
export interface _SERVICE {
  'getAllDonuts' : ActorMethod<[], Array<Donut>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getDonutById' : ActorMethod<[bigint], Donut>,
  'getDonutsByCategory' : ActorMethod<[string], Array<Donut>>,
  'getOrderById' : ActorMethod<[bigint], Order>,
  'placeOrder' : ActorMethod<
    [string, string, string, Array<[bigint, bigint]>],
    bigint
  >,
  'searchDonuts' : ActorMethod<[string], Array<Donut>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];