/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Donut = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const OrderItem = IDL.Record({
  'donutId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'customerPhone' : IDL.Text,
  'timestamp' : IDL.Int,
  'items' : IDL.Vec(OrderItem),
  'customerEmail' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllDonuts' : IDL.Func([], [IDL.Vec(Donut)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getDonutById' : IDL.Func([IDL.Nat], [Donut], ['query']),
  'getDonutsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Donut)], ['query']),
  'getOrderById' : IDL.Func([IDL.Nat], [Order], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      [IDL.Nat],
      [],
    ),
  'searchDonuts' : IDL.Func([IDL.Text], [IDL.Vec(Donut)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Donut = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const OrderItem = IDL.Record({ 'donutId' : IDL.Nat, 'quantity' : IDL.Nat });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'customerPhone' : IDL.Text,
    'timestamp' : IDL.Int,
    'items' : IDL.Vec(OrderItem),
    'customerEmail' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllDonuts' : IDL.Func([], [IDL.Vec(Donut)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getDonutById' : IDL.Func([IDL.Nat], [Donut], ['query']),
    'getDonutsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Donut)], ['query']),
    'getOrderById' : IDL.Func([IDL.Nat], [Order], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
        [IDL.Nat],
        [],
      ),
    'searchDonuts' : IDL.Func([IDL.Text], [IDL.Vec(Donut)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };